### ISSUE TITLE
[QUESTION]: how did you get drama list?

### ISSUE THREAD

**Issue by devvsakib** [guilherssousa/dramaland#2]
hi, sorry for raising an issue. I want to know how did you get this json data. I mean do you have any API for kdrama?

**Comment by guilherssousa** [comment]
No, actually I wrote a DOM scrapping script and ran it against MyDramaList website via DevTools, the script only did some querySelectors and formatted the content as JSON. I think I forgot to save the code as a gist, but this is a technique that I always do when I want to grab information from sources when there is no public API available.
